language: cpp
dist: xenial
sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            - expect
            - gettext
            - libncurses5-dev
            - libpcre2-dev
            - python3
            - python3-pip
      before_install:
        - sudo pip3 install pexpect
      env:
          # Some warnings upgraded to errors to match Open Build Service platforms
          - CXXFLAGS="-Werror=address -Werror=return-type"
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages: # Don't use libpcre2-dev here, so that one build uses the vendored code
            - expect
            - gettext
            - lib32ncurses5-dev
            - g++-multilib
            - python3
            - python3-pip
      before_install:
        - sudo pip3 install pexpect
      env:
          - CXXFLAGS="-m32 -Werror=address -Werror=return-type" CFLAGS="-m32"
    - os: linux
      compiler: clang
      env:
          - CXXFLAGS="-fno-omit-frame-pointer -fsanitize=undefined -fsanitize=address"
          - ASAN_OPTIONS=check_initialization_order=1:detect_stack_use_after_return=1:detect_leaks=1
          - UBSAN_OPTIONS=print_stacktrace=1:report_error_type=1:suppressions=$TRAVIS_BUILD_DIR/build_tools/ubsan.blacklist
      before_install:
        - sudo pip3 install pexpect
      addons:
        apt:
          packages:
            - expect
            - gettext
            - libncurses5-dev
            - libpcre2-dev
            - python
            - python3
            - python3-pip
    - os: linux
      compiler: clang
      env:
          - CXXFLAGS="-fsanitize=thread"
      before_install:
        - sudo pip3 install pexpect
      addons:
        apt:
          packages:
            - expect
            - gettext
            - libncurses5-dev
            - libpcre2-dev
            - python3
            - python3-pip
    - os: linux
      compiler: gcc
      addons:
        coverity_scan:
          project:
            name: "fish-shell/fish-shell"
            description: "The friendly interactive shell"
          notification_email: corydoras@ridiculousfish.com
          build_command_prepend: "mkdir -p build; cd build; cmake -G Ninja .."
          build_command: "ninja"
          branch_pattern: coverity_scan_master
        apt:
          packages:
            - expect
            - gettext
            - libncurses5-dev
            - libpcre2-dev
            - python3
            - python3-pip
      before_install:
        - sudo pip3 install pexpect
        - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
      env:
          - secure: "Q1AS5iEi17s+xsRaMwfkxmm62UDaV47uE39pvXsNL+DO9YWbMMuhTpIOeYhxLvFNL3LMUFU2TwVpVRYX2YFGhNNaMSmjQfyQ+7q7/oSEo0aSqvQkwelpK/pwuRAXdv1MU4aQ6FrCEQ4VMO45WRo0o5WD26pvxjqRyAQ6ry+serA="
          # Some warnings upgraded to errors to match Open Build Service platforms
          - CXXFLAGS="-Werror=address -Werror=return-type"
    - os: osx
      before_install:
        - sudo pip3 install pexpect
  fast_finish: true

script:
  - cmake -DCMAKE_INSTALL_PREFIX=$HOME/prefix . || cat CMakeFiles/CMakeError.log &&
    make -j2 &&
    make install &&
    make test SHOW_INTERACTIVE_LOG=1

notifications:
  # Some items are encrypted so that notifications from other repositories
  # don't flood the official repositories.
  irc:
    channels:
        #- "irc.oftc.net#fish"
        secure: "eRk9KGZ5+mrlD2SoI8yg2Sp8OYrh7YPyGe3WCDQUwTnNgNDII34rbM9a6UOA/l7AeWSNY8joLq5xVLCU4wpFgUcJ11SYIpMnLosZK29OW4ubDOHmdBDvJ971rLgAVG9cXngZtIxEVVxN/jnS1Qr8GKZx4DjkaTMgz1pemb4WxCc="
    template:
      - "%{repository}#%{build_number} (%{commit} on %{branch} by %{author}): %{message} Details at %{build_url}"
    use_notice: true
    skip_join: true
  webhooks:
    urls:
      #- https://webhooks.gitter.im/e/61821cec3015bf0f8bb1
      secure: fPfOmxnC3MCsfR1oocVFeWLawGcRZkn+8fNHlSOeZ+SqqoZfcCHgQTvQ22TqmVl1yvkXbNlaXjo6dbVzTOAh7r7H0bRMEKBVh3dQS7wqjB1sKivpXd8PAS3BTj5MQpGeJzdHnDuwVlwDktGtfHfhGeq1Go/4IosOq8u+6RTe28g=
